import type { StaffMember } from "@/lib/schemas/staff"

export const mockStaff: StaffMember[] = [
    {
        id: "1",
        firstName: "Sarah",
        lastName: "Mitchell",
        role: "Emergency Physician",
        department: "Emergency",
        email: "s.mitchell@ercareview.com",
        phone: "03 9000 0001",
        availability: "available",
    },
    {
        id: "2",
        firstName: "James",
        lastName: "Nguyen",
        role: "Triage Nurse",
        department: "Emergency",
        email: "j.nguyen@ercareview.com",
        phone: "03 9000 0002",
        availability: "busy",
    },
    {
        id: "3",
        firstName: "Priya",
        lastName: "Sharma",
        role: "Radiologist",
        department: "Radiology",
        email: "p.sharma@ercareview.com",
        phone: "03 9000 0003",
        availability: "available",
    },
    {
        id: "4",
        firstName: "Tom",
        lastName: "Bradley",
        role: "Surgical Registrar",
        department: "Surgery",
        email: "t.bradley@ercareview.com",
        phone: "03 9000 0004",
        availability: "off-duty",
    },
    {
        id: "5",
        firstName: "Aisha",
        lastName: "Rahman",
        role: "ICU Nurse",
        department: "Intensive Care",
        email: "a.rahman@ercareview.com",
        phone: "03 9000 0005",
        availability: "available",
    },
    {
        id: "6",
        firstName: "David",
        lastName: "Park",
        role: "Cardiologist",
        department: "Cardiology",
        email: "d.park@ercareview.com",
        phone: "03 9000 0006",
        availability: "busy",
    },
    {
        id: "7",
        firstName: "Emma",
        lastName: "Wilson",
        role: "Pediatric Nurse",
        department: "Pediatrics",
        email: "e.wilson@ercareview.com",
        phone: "03 9000 0007",
        availability: "available",
    },
    {
        id: "8",
        firstName: "Marcus",
        lastName: "Thompson",
        role: "Anesthesiologist",
        department: "Surgery",
        email: "m.thompson@ercareview.com",
        phone: "03 9000 0008",
        availability: "off-duty",
    },
]
